services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/images:/usr/src/app/images
    ports:
      - "8081:8081"
